/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_BRCoreMasterPubKey */

#ifndef _Included_com_breadwallet_core_BRCoreMasterPubKey
#define _Included_com_breadwallet_core_BRCoreMasterPubKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_core_BRCoreMasterPubKey
 * Method:    serialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_breadwallet_core_BRCoreMasterPubKey_serialize
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_core_BRCoreMasterPubKey
 * Method:    getPubKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_breadwallet_core_BRCoreMasterPubKey_getPubKey
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_core_BRCoreMasterPubKey
 * Method:    createPubKey
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_BRCoreMasterPubKey_createPubKey
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_core_BRCoreMasterPubKey
 * Method:    createJniCoreMasterPubKeyFromPhrase
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_BRCoreMasterPubKey_createJniCoreMasterPubKeyFromPhrase
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_breadwallet_core_BRCoreMasterPubKey
 * Method:    createJniCoreMasterPubKeyFromSerialization
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_BRCoreMasterPubKey_createJniCoreMasterPubKeyFromSerialization
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_breadwallet_core_BRCoreMasterPubKey
 * Method:    bip32BitIDKey
 * Signature: ([BILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_breadwallet_core_BRCoreMasterPubKey_bip32BitIDKey
  (JNIEnv *, jclass, jbyteArray, jint, jstring);

/*
 * Class:     com_breadwallet_core_BRCoreMasterPubKey
 * Method:    validateRecoveryPhrase
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_breadwallet_core_BRCoreMasterPubKey_validateRecoveryPhrase
  (JNIEnv *, jclass, jobjectArray, jstring);

/*
 * Class:     com_breadwallet_core_BRCoreMasterPubKey
 * Method:    generatePaperKey
 * Signature: ([B[Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_breadwallet_core_BRCoreMasterPubKey_generatePaperKey
  (JNIEnv *, jclass, jbyteArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
