## This is a script to enter the mnemonic to an android phone in the recovery page
## Please complete the words as you wish and do not edit this file
## TEST-NET
adb shell input text ""
adb shell input keyevent 61
adb shell input text ""
adb shell input keyevent 61
adb shell input text ""
adb shell input keyevent 61
adb shell input text ""
adb shell input keyevent 61
adb shell input text "fault"
adb shell input keyevent 61
adb shell input text "ski"
adb shell input keyevent 61
adb shell input text "profit"
adb shell input keyevent 61
adb shell input text "awkward"
adb shell input keyevent 61
adb shell input text "favorite"
adb shell input keyevent 61
adb shell input text "worth"
adb shell input keyevent 61
adb shell input text "stem"
adb shell input keyevent 61
adb shell input text "man"