# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-29-ndk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      SDK_FILENAME: sdk-tools-linux-4333796.zip
      ANDROID_HOME: /opt/android/sdk


    steps:
      - checkout

      #Check init
      - run:
          name: check init
          command: |
            echo $PWD
            ls -la .
            ls -la $ANDROID_HOME
      # Download and cache dependencies gradle
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}


      #Refresh gradle
      - run:
          name: Refresh gradle
          command: |
            ./gradlew   dependencies

      #gradle build
      - run:
          name: gradle detekt
          command: |
            ./gradlew --console=plain detekt

      #gradle build
      - run:
          name: gradle test
          command: |
            ./gradlew  --console=plain testBrdDebugUnitTest testBrdTestnetDebugUnitTest

      # save cache
      - save_cache:
          paths:
            - ~/.gradle

          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}



      # save tests!
      - run:
          name: Save test results
          command: |
            mkdir -p ~/atrifact
            ls -l ./app/build
            cp -r ./app/build/reports ~/atrifact;
            cp -r ./app/build/test-results ~/atrifact;
          when: always
      - store_test_results:
          path: ./app/build/test-results
      - store_artifacts:
          path: ~/atrifact



workflows:
  version: 2
  commit:
    jobs:
      - build
