/**
 * BreadWallet
 *
 * Created by Drew Carlson <drew.carlson@breadwallet.com> on 6/30/20.
 * Copyright (c) 2020 breadwallet LLC
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.breadwallet.tools.util

val coingeckoIdMap = mapOf(
    "BTC" to "bitcoin",
    "BCH" to "bitcoin-cash",
    "ETH" to "ethereum",
    "HBAR" to "hedera-hashgraph",
    "XRP" to "ripple",
    "1ST" to "first-blood",
    "ABT" to "arcblock",
    "ADT" to "adtoken",
    "ADX" to "adex",
    "AE" to "aeternity",
    "AGI" to "singularitynet",
    "AION" to "aion",
    "AMB" to "amber",
    "AMLT" to "coinfirm-amlt",
    "ANT" to "aragon",
    "APPC" to "appcoins",
    "ARN" to "aeron",
    "ATMI" to "atonomi",
    "AUTO" to "cube",
    "BIX" to "bibox-token",
    "BLZ" to "bluzelle",
    "BNB" to "binancecoin",
    "BNT" to "bancor",
    "BRD" to "bread",
    "BTM" to "bytom",
    "CAS" to "cashaa",
    "CFI" to "cofound-it",
    "CMT" to "cybermiles",
    "CND" to "cindicator",
    "CNN" to "cnn",
    "CRPT" to "crypterium",
    "CS" to "credits",
    "CSP" to "caspian",
    "CVC" to "civic",
    "DAI" to "dai",
    "DENT" to "dent",
    "DGD" to "digixdao",
    "DNT" to "district0x",
    "DOV" to "dovu",
    "DRGN" to "dragonchain",
    "EDG" to "edgeless",
    "EDO" to "eidoo",
    "ELF" to "aelf",
    "ENG" to "enigma",
    "ENJ" to "enjincoin",
    "EOS" to "eos",
    "FSN" to "fsn",
    "FUN" to "funfair",
    "FXC" to "flexacoin",
    "GBX" to "globitex",
    "GNO" to "gnosis",
    "GNT" to "golem",
    "GNX" to "genaro-network",
    "GTO" to "gifto",
    "GUP" to "matchpool",
    "GUSD" to "gemini-dollar",
    "GVT" to "genesis-vision",
    "HPB" to "high-performance-blockchain",
    "HYDRO" to "hydro",
    "ICN" to "ic-node",
    "ICX" to "icon",
    "IOST" to "iostoken",
    "ITC" to "iot-chain",
    "IXT" to "insurex",
    "KIN" to "kin",
    "KNC" to "kyber-network",
    "LEND" to "ethlend",
    "LINK" to "chainlink",
    "LOOM" to "loom-network",
    "LRC" to "loopring",
    "LUN" to "lunyr",
    "MAN" to "matrix-ai-network",
    "MANA" to "decentraland",
    "MCO" to "monaco",
    "MKR" to "maker",
    "MTL" to "metal",
    "MYST" to "mysterium",
    "NAS" to "nebulas",
    "NEXO" to "nexo",
    "NMR" to "numeraire",
    "NPXS" to "pundi-x",
    "NULS" to "nuls",
    "OMG" to "omisego",
    "OST" to "simple-token",
    "OXT" to "orchid-protocol",
    "PAL" to "policypal",
    "PAX" to "paxos-standard",
    "PAY" to "tenx",
    "POE" to "poet",
    "POLY" to "polymath-network",
    "POWR" to "power-ledger",
    "PPT" to "populous",
    "PTOY" to "patientory",
    "QASH" to "qash",
    "QRL" to "quantum-resistant-ledger",
    "QSP" to "quantstamp",
    "RCC" to "reality-clash",
    "RCN" to "ripio-credit-network",
    "RDN" to "raiden-network",
    "REP" to "augur",
    "REQ" to "request-network",
    "REV" to "revain",
    "RLC" to "iexec-rlc",
    "RUFF" to "ruff",
    "RVT" to "rivetz",
    "SAI" to "sai",
    "SALT" to "salt",
    "SAN" to "santiment-network-token",
    "SENT" to "sentinel-group",
    "SNC" to "suncontract",
    "SNGLS" to "singulardtv",
    "SNM" to "sonm",
    "SNT" to "status",
    "SRN" to "sirin-labs-token",
    "STK" to "stk",
    "STMX" to "storm",
    "STORJ" to "storj",
    "STQ" to "storiqa",
    "STU" to "bitjob",
    "STX" to "stox",
    "SUB" to "substratum",
    "TEL" to "telcoin",
    "THETA" to "theta-token",
    "TIME" to "chronobank",
    "TRX" to "tron",
    "TUSD" to "true-usd",
    "UCASH" to "ucash",
    "USDC" to "usd-coin",
    "VEE" to "blockv",
    "VGX" to "ethos",
    "VIB" to "viberate",
    "WINGS" to "wings",
    "WPR" to "wepower",
    "WRC" to "worldcore",
    "WTC" to "waltonchain",
    "XUC" to "exchange-union",
    "ZIL" to "zilliqa",
    "ZLA" to "zilla",
    "ZRX" to "0x",
    "NCASH" to "nucleus-vision"
)