/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_ethereum_BREthereumNetwork */

#ifndef _Included_com_breadwallet_core_ethereum_BREthereumNetwork
#define _Included_com_breadwallet_core_ethereum_BREthereumNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_core_ethereum_BREthereumNetwork
 * Method:    jniGetMainnet
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_ethereum_BREthereumNetwork_jniGetMainnet
  (JNIEnv *, jclass);

/*
 * Class:     com_breadwallet_core_ethereum_BREthereumNetwork
 * Method:    jniGetTestnet
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_ethereum_BREthereumNetwork_jniGetTestnet
  (JNIEnv *, jclass);

/*
 * Class:     com_breadwallet_core_ethereum_BREthereumNetwork
 * Method:    jniGetRinkeby
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_ethereum_BREthereumNetwork_jniGetRinkeby
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
