/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_ethereum_BREthereumAccount */

#ifndef _Included_com_breadwallet_core_ethereum_BREthereumAccount
#define _Included_com_breadwallet_core_ethereum_BREthereumAccount
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
