/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_core_ethereum_BREthereumToken */

#ifndef _Included_com_breadwallet_core_ethereum_BREthereumToken
#define _Included_com_breadwallet_core_ethereum_BREthereumToken
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_core_ethereum_BREthereumToken
 * Method:    getAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_breadwallet_core_ethereum_BREthereumToken_getAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_core_ethereum_BREthereumToken
 * Method:    getSymbol
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_breadwallet_core_ethereum_BREthereumToken_getSymbol
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_core_ethereum_BREthereumToken
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_breadwallet_core_ethereum_BREthereumToken_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_core_ethereum_BREthereumToken
 * Method:    getDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_breadwallet_core_ethereum_BREthereumToken_getDescription
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_core_ethereum_BREthereumToken
 * Method:    getDecimals
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_breadwallet_core_ethereum_BREthereumToken_getDecimals
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_core_ethereum_BREthereumToken
 * Method:    getColorLeft
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_breadwallet_core_ethereum_BREthereumToken_getColorLeft
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_core_ethereum_BREthereumToken
 * Method:    getColorRight
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_breadwallet_core_ethereum_BREthereumToken_getColorRight
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_core_ethereum_BREthereumToken
 * Method:    jniGetTokenBRD
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_core_ethereum_BREthereumToken_jniGetTokenBRD
  (JNIEnv *, jclass);

/*
 * Class:     com_breadwallet_core_ethereum_BREthereumToken
 * Method:    jniTokenAll
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_com_breadwallet_core_ethereum_BREthereumToken_jniTokenAll
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
